### ISSUE TITLE
maven 导入失败。

### ISSUE THREAD

**Issue by xdmdcp** [qrpcode/wordgo#1]
如图，导入失败，请问作者有更好的解决办法吗？

![image](https://user-images.githubusercontent.com/37510077/92319979-79383c80-f050-11ea-982f-36b2310b48c7.png)

**Comment by qrpcode** [comment]
亲，尝试下使用阿里云的国内镜像，目前阿里云镜像上面应该是有的
PS：
阿里云镜像地址：http://maven.aliyun.com/nexus/content/groups/public
设置方式：https://blog.csdn.net/u012702547/article/details/88071279

**Comment by xdmdcp** [comment]
@qrpcode 非常感谢，我已经采用jar导入使用。不过如果maven能导入会更好，辛苦博主答复。
